name: GitVersion Lab

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  version-lab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@master
        id: nbgv
      - run: echo "Version=${{ steps.nbgv.outputs.SemVer2 }}"
